### PR TITLE
👤mommy now refers to the user using $USER var~

### PR DESCRIPTION
**Pull request by Bikoil**
Heya! So I made the program use for the `MOMMY_SWEETIE` variable instead of just "girl" to use the `$USER` variable

This is a very small addition that I thought would fit pretty good, so it's more universal

Also, I was gonna open this pull request in your dev branch, but It doesn't seem to exist, So I had to open it in main

### CODE REVIEW

**Comment by FWDekker** [comment]
cool! good idea, actually.

a few requests:
1. could you replace `$USER` by `$LOGNAME`? surprisingly, `$USER` is not POSIX, so if we use `$USER` some shells might get an empty string instead.
2. in fact, replace `$USER` by `${LOGNAME:-girl}`, so that, if `$LOGNAME` is unset or empty (somehow), the default becomes `girl`. (if you have a better suggestion for `girl`, let me know!)
3. could you add this to the `README.md`? in the section configuration, in the _list of all settings_, the default value of `MOMMY_SWEETIE` should be set to "\<username\>".

**Comment by Bikoil** [comment]
> cool! good idea, actually.
> 
> a few requests:
> 1. could you replace `$USER` by `$LOGNAME`? surprisingly, `$USER` is not POSIX, so if we use `$USER` some shells might get an empty string instead.
> 2. in fact, replace `$USER` by `${LOGNAME:-girl}`, so that, if `$LOGNAME` is unset or empty (somehow), the default becomes `girl`. (if you have a better suggestion for `girl`, let me know!)
> 3. could you add this to the `README.md`? in the section configuration, in the _list of all settings_, the default value of `MOMMY_SWEETIE` should be set to "\<username\>".
> 
> as for the `dev` branch thing: thanks for noticing that! that's from an old workflow, i'll make sure to remove that from the contributing.md :-)


No problem at all! I'll set those up instantly when I can, Thanks

**Comment by Bikoil** [comment]
@FWDekker Alright changes have been made, you can tell me if you want to change anything in it or if you want to merge it or not :D

**Comment by FWDekker** [comment]
thanks for the changes!

euhm, yeah, looks like your editor quite aggressively adds/removes whitespace. unfortunately, some of that whitespace is actually important for the layout. i've undone those changes now :-)

i'll merge the changes after all ci returns positive! :)

**Comment by FWDekker** [comment]
i had to rebase your changes to fix and test something in a separate branch first, but it all works now! :)

**Comment by Bikoil** [comment]
ty! :D

**Pull request merged**
